name: savi

services:
  savi:
    image: jeremy28g/savi:latest
    container_name: savi_app
    restart: unless-stopped

    ports:
      - "127.0.0.1:8000:8000"

    env_file:
      - .env

    environment:
      DATABASE_PATH: /app/data/db.sqlite3
      REDIS_URL: redis://redis:6379/0

    volumes:
      - sqlite_data:/app/data

    extra_hosts:
      - "host.docker.internal:host-gateway"

    depends_on:
      - chromadb
      - redis

  chromadb:
    image: chromadb/chroma:latest
    container_name: savi_chroma
    restart: unless-stopped

    expose:
      - "8000"

    volumes:
      - chroma_data:/chroma/chroma

  redis:
    image: redis:7-alpine
    container_name: savi_redis
    restart: unless-stopped

    expose:
      - "6379"

volumes:
  chroma_data:
    name: savi_chroma_data
  sqlite_data:
    name: savi_sqlite_data
